### PR TITLE
Update probe-rs, probe-rs-rtt to 0.12

### PR DESCRIPTION
**Pull request by korken89**
Probe-rs 0.12 was just released. This updates the dependency and fixes the breaking changes.

Tested the binary using an STM32 Nucleo devboard.

### CODE REVIEW

**Review by jonathanpallant — APPROVED** [review]

**Comment by jonathanpallant** [comment]
Thanks for this @korken89! I'm very excited to see RP2040 support :)

Works OK for me on an STM32 Nucleo as well. Would like to hear from @japaric or @jonas-schievink or someone with an nRF52840 just as a double-check before merging though.

**Comment by jonathanpallant** [comment]
Edit, works OK on the Raspberry Pi Pico too (using a second Pico running [the CMSIS-DAP firmware](https://github.com/majbthrd/DapperMime)).

**Comment by newAM** [comment]
This fixes #255

**Comment by jonas-schievink** [comment]
A quick test on the nRF52840 seems to work fine as well

**Comment by newAM** [comment]
Would it be possible to get a release with this change included?  This would help out a lot of people using the STM32WL; it fixes #255 and https://github.com/stm32-rs/stm32wlxx-hal/issues/74.

**Pull request merged**
