### PR TITLE
Handle reset vector not pointing to ELF symbol

### LINKED ISSUE #391: Unable to determine reset handler
**Describe the bug**
Since updating to latest probe-run today, I'm getting this error when trying to run my RP2040 code.

**To Reproduce**
1. Run any RP2040 program with `probe-run --chip RP2040 <path>`

**Expected and observed behavior**
Expected probe-run to remain open while printing output from RP2040 as before.

Instead, getting this output:
```(HOST) INFO  flashing program (12 pages / 48.00 KiB)
(HOST) INFO  success!
Error: unable to determine reset handler
```

**config.toml**
The contents of your project's `.cargo/config.toml` file

```toml
[target.thumbv6m-none-eabi]
runner = "probe-run --chip RP2040"
rustflags = [
    "-C", "linker=flip-link",
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-LUiFirmware",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "link-arg=-Tlink.x",
    "-C", "inline-threshold=5",
    "-C", "no-vectorize-loops",
]
```

**Probe details**
```[0]: Picoprobe CMSIS-DAP (VID: 2e8a, PID: 000c, Serial: E6614864D35F8C21, CmsisDap)```

**Operating System:**
Linux running under WSL

**Additional context**
Like mentioned above, things worked as expected with the previous version.

### PR DESCRIPTION
**Pull request by jannic**
Closes #391

### CODE REVIEW

**Comment by jannic** [comment]
Output of running `probe-run --chip RP2040 target/thumbv6m-none-eabi/debug/rp2040-project-template -v` and then aborting with CTRL-C, with the fixed binary:
[probe-run.log](https://github.com/knurling-rs/probe-run/files/11214602/probe-run.log)

**Review by jonathanpallant — APPROVED** [review]
LGTM. Thanks!

**Comment by jannic** [comment]
> Merge conflict.

I'll have a look.

**Comment by Urhengulas** [comment]
bors retry

Thank you for your work @jannic

**Pull request merged**
