### PR TITLE
README.md: Add troubleshooting for use with RTIC

### PR DESCRIPTION
**Pull request by davidlattimore**
Additional context:
https://github.com/knurling-rs/defmt/issues/450

### CODE REVIEW

**Review by Urhengulas — CHANGES_REQUESTED** [review]
Generally looks good to me.

One nit: Can you add some more lines to make the code snippets more "copy-pastable"? For the first one it's probably only some import, for the second maybe some type information for `ctx`.

**Comment by davidlattimore** [comment]
I expanded the second one to include the signature of the init function, which includes the ctx argument. `init` and `idle` come from the RTIC procedural macro. I could include a full RTIC program, but that might be a bit too much?

**Comment by Urhengulas** [comment]
> I could include a full RTIC program, but that might be a bit too much?

Yes, that would be too much. Someone facing this problem likely knows the structs, I guess.

Looks good to me now. Thanks a lot!

**Review by Urhengulas — APPROVED** [review]
bors r+

**Pull request merged**
